ENV_POSTGRES_SERVICEDB_URL: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_TCP_5432:5432}/intentpicker
ENV_POSTGRES_SERVICEDB_USERNAME: test
ENV_POSTGRES_SERVICEDB_PASSWORD: test
ENV_POSTGRES_SERVICEDB_FLYWAY_USERNAME: test
ENV_POSTGRES_SERVICEDB_FLYWAY_PASSWORD: test
ENV_SECURE_KAFKA_DISCOVERY_BOOTSTRAP_SERVER: ${KAFKA_HOST:localhost}:${KAFKA_TCP_9092:9092}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.apache: WARN
    kafka: WARN
