services:
  zookeeper:
    image: docker-hub.tw.ee/zookeeper:latest
    hostname: zookeeper
    ports:
      - "${ZOOKEEPER_PORT_MAPPING}"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -server -Xms25m -Xmx512m -XX:+UseG1GC -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -noverify -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
  kafka:
    image: docker-hub.tw.ee/wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "${KAFKA_PORT_MAPPING}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      PORT_COMMAND: "docker port $$(docker ps -q -f name=kafka) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:_{PORT_COMMAND},INTERNAL://kafka:9093"
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 10000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      LOG4J_LOGGER_ORG: WARN,STDOUT
      LOG4J_LOGGER_ORG_APACHE_KAFKA: WARN,STDOUT
      LOG4J_LOGGER_KAFKA: WARN,STDOUT
      KAFKA_JVM_PERFORMANCE_OPTS: -server -Xms25m -Xmx512m -XX:+UseG1GC -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -noverify -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -Dcom.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.fastBoot=true -XX:+AggressiveOpts -Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: docker-hub.tw.ee/postgres:12.16-alpine
    ports:
      - "${POSTGRES_PORT_MAPPING}:5432"
    environment:
      POSTGRES_DB: intentpicker
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: "-c 'max_connections=200'"
